## Famous books, authors and people, and their works

- Stolen Images: Lain Singh Wangdel
- Akash Bivajit Cha: book written by 10 authors of Nepal
- Palpasa Cafe/ Mayur Times: Narayan Wagle
- Seto Dharti/ Karodau Kasturi: Amar Neupane (2069 Madan Prize winner)
- Radha/ Jhola/ Adhabato: Krishna Dharabashi
- Jail Journal/ Babu Ama ra Chora/ Hitler ra Yahudi/ Doshi Chasma: B.P.Koirala
- Jiwan Kanda Ki Full: Jhamak Ghimire (2068 Madan Prize winner)
- Karnali Blues/ Phirpire: Buddi Sagar
- Damini Veer: Rajan Mukarung (2070 Madan Prize winner)
- Summer Love/ Saya: Subin Bhattarai
- Khalanga Ma Hamala: Radha Poudel (2071 Madan Prize winner)
- Zoya: Daniel Steel
- The Alchemist: Paulo Coelho
- War and Peace: Leo Tolstoy
- Mother: Maxim Gorkey
- Long Walk to Freedom: Nelson Mandela
- Paradise Lost: John Milton
- Harry Potter: J.K. Rowling
- Maile Dekheko Nepal: Dr. Harka Gurung
- The Three Mistakes of My Life: Chetan Bhagat
- Das Capital: Karl Marx
- My Experiment with Truth: Mahatma Gandhi

- Miss Nepal 2016: Ashmi Shrestha            
- Miss Nepal Earth: Roshani Khatri
- Miss Nepal International: Barsha Lekhi
- Miss World 2015: Mireia Lalaguna (Spain)
- Miss World 2016 is going to be held in Washington D.C., USA
- Miss Universe 2015: Pia Urtzbech (Philippines)
- Miss Universe 2016 is going to be held in Philippines.

- Kathmandu University was established in 2048 B.S.
- Province 2 has the highest population density.
- "Time zero" (Sunnya samaya) was written by Yubraj Ghimire.
- According to 2068 survey, there are 64.63% mobile phone users.
- Padmashree literature accolade of 2075 was handed to Ramesh Sayaan's "Chutteka Anuhar"
- Padmashree sadhana accolade of 2075 was handed to historian Maheshraj Panta.
- Minestrial cabinet first held their meeting with video conference in 2076, Bhadra 9.
- The hurricane that struck Bara-Parsa in Bhadra 8 was named Dhumrapat.
- Mr. Surendra Prasad Yadav was appointed chairman of Civil Service Commission of Province 2 on Bhadra 5.
- "Yuva Moti Puraskar" of 2075 was given to Shankar Chapagain (Dhankute Kancha) and Fulman Bal.
- Nepal Government's legal advisor is Chief Justice ("Mahanyadibakta")
- Gautam Buddha communicated his learnings for 45 years.
- Brazil is the country where sour honey can be found. ?
- In San Marino, there are two presidents.
- Moroccoo is the country where Red Salt is found.
- In the Shree-Swasthani Puran (a branch of Skanda puran), there are 8110 slokas.
- Full name of "Ohm" is George Simon Ohm.
- Nepals goals (by):
  - Ending child marriage: 2020 AD
  - Filariasis parasite eradication: 2020 AD
  - Transition to developing country status: 2022 AD
  - Birth rate substitution: 2022 AD
  - Doubling tiger's population: 2022 AD
  - Eradication of hunger: 2025 AD
  - Malaria eradication: 2025 AD
  - Hydroelectricity independence: 2027 AD
  - Ending of poverty: 2030 AD
  - Middle income status achievement: 2030 AD
- Which was the disease to be completely eradicated from the world: Measles.
- During Rana regime, transaction of gold, silver and valuables was done by "Bintipatra Niksari Adda".
- Ancientmost religion of Nepal is the "Saiba"
- Annual population growth rate was highest in 2038 BS.
- Article 242 of Nepal's constitution has provision for civil serivce commission.
- "Urab" is the caste that is recognized by its occupation of farming.
- India launched the Chandrayan-2 rocket on July 22, 2019.
- Madan puraskar, 2075 was awarded to Yogesh Raj's "Ranahar".
- Jagadamba shree prize, 2075 was awarded to Bairagi kaila (Til Bikram Nembang).
- Ministry of Civil Aviation and Tourism was chaired by Yogesh Bhattarai in Shrawan 15, 2076.
- International Youth Year, 2019 had slogan: "Transforming education"
- Shuvadra Adhikari (Actress) died in Shrawan 32, 2076.
- Indian foreign minister Shusma Shwaraj died on August 6, 2019.
- Province number 5 was the earliest among provinces to appoint Civil Service Commission chairman (Dr. Dilaram Bhattarai).
- Senior literary figure Madanmani Dixit died on Shrawan 30, 2076.
- 4th national forest day's slogan was "Samudayik Ban ma Nabintam Soch, Utpadan, Uddhyam ra Samriddhi ma Jodd"
- Indian government withdrew the special previlage it had been granting Kashmir based on constitutional article 370 on August 5, 2019.
- Indian national to be awarded Roman Magases prize in 2019 was Journalist Ravish Kumar.
- ICC world test championship started on Aug 1, 2019.
- Nepal first took map of the country via its satellite "Nepal Sat-1" on August 3, 2019.
- Gyanchandra Acharya was elected vice secretary of alliance of least developed and land locked countries of UN in August 14, 2012.
- According to UN report, 1/3 rd of the total food goes waste.
- Since 2008 AD, WHO started observing World Malaria day every 25th of April.
- The first female chief of the IMF was Christina Glagards (France).
- Country to first grow seedling in the outer space was China.
- Ramjanaki temple is in the Dhanusha district.
- Goitre is caused by the deficiency of iodine.
- Ten writers jointly wrote the publication: "Aakash bivajit chha"
- Simikot is the headquarters of Humla district, which also happens to be the headquarters at the highest altitude.
- Youngest mountaineer to have climbed the Mount Everest is Dorje Sherpa.
- Currently, local development minister is Lal Babu Pandit.
- Bamboo is the quickest growing plant.
- Madan Ashrit highway is 36.16 km in length.
- The inventor of parachute was Joe Blanchard.
- Water is heaviest at 40 degree F.
- Human blood is 6 times more viscous than water.
- A cat sleeps 16 hours in a day.
- Nepal's constitution day is celebrated on Ashoj 3.
- "Dying is begin born again": Shukraraj Shastri
- A person who transcribes others' writing word by word is called a ghost writer.
- Amar Singh Thapa died in the battle of Palanchowk.
- Mendel's pea had 7 pairs of contrasting characters.
- Nepal government initiated the cancer protocol on 25th Baisakh, 2074.
- Britain's first woman PM is Margaret Thatcher.
- An instrument for lie detection is called Polygraph.
- Amar Neupane wrote "Karodau Kasturi".
- Satya Mohan Joshi is a Nepali writer and scholar.
  -	He is famous for his research on history and culture of Nepal. 
  -	He is working now as the chancellor for Nepal Basa Academy
  -	He was born in 1920 in Lalitpur
  -	He has following publications: Haamro lok sanskriti, Kalakar Arniko, Sunkhesari, Majipa Lakhe.
- China and Nepal recently agreed upon opening up following borders for ? when ?:
  - Tinker: Darchula
  - Kimathanka: Sankhuwasabha
  - Yari: Humla
  - Kodari tatopani: Sindhupalchowk
  - Olangchungola: Taplejung
  - Rasuwagadhi: Rasuwa
- National innovation center was established in Nov 9, 2012
- National Academy of Science and Technology was established in 1982
- Bonn challenge: https://en.wikipedia.org/wiki/Bonn_Challenge
- Ministry of forests and environment reports: https://mofe.gov.np/downloadsdetail/3/2018/98853603/
- Department of wildlife conservation: http://www.dnpwc.gov.np/en/project/

**Important metric conversions**

- 1 hectare = 10000m2 = 30 katha = 20 ropani = 2.47 acre = 1.5 bigha
- 1 bigha = 20 katha = 13.31 ropani
- 1 ropani = 16 anna = 508.5m2
- 1 katha = 20 dhur = 338.6m2
- 1 pathi = 8 mana
- 1 mana = 568 ml
- 1 muri = 20 pathi
- 1 ton = 1000 kg
- 1 kg = 2.2 pound
- 1 pound = 16 ounce
- 1 inch = 2.54 cm
- 1 gallon = 4.5 ltr

**Some Revolutions**

- Black Revolution: Petroleum Production
- Green Revolution: (1965/66) in Agriculture
- White Revolution: Related to milk production or operation
- Blue Revolution: Fisheries production
- Brown Revolution: Leather/Cocoa production
- Golden Revolution: horticulture production/ honey production
- Golden Fiber Revolution: Jute production
- Gray Revolution: Fertilizer production
- Pink Revolution: Onion/ Prawn production
- Red Revolution: Meat/tomato production
- Silver Revolution: Egg/ Poultry production
- Yellow Revolution: production of oilseeds
- Round Revolution: Potato production
- Fibre Revolution: Cotton production
- Rainbow Revolution: Agriculture

- 1st Myagassae Prize Winner: Tulshi Mehar Shrestha
- Most comedy picture in Facebook: Chinese Basketball player Yaw Ming
- Director of movie Slumdog Millionaire: Dany Boyle
- Director of movie Titanic and Avatar: James Cameroon
- Number of national parks in the World is about 7000.
- Baburam Acharya coined the name Sagarmatha for Mt.Everest
- Number of pointed sides in the sun of national flag of Nepal is 12 and in the moon is 8.
- Bird found only in Nepal: Kande Bhyakur (Spiny babbler)
- Founder of Google: Larry Page and Sargey Brin (meaning of Google is 1000 zeros after one)
- Founder of Facebook: Mark Zuckerberg
- Founder of Yahoo: Jerry Yang and David Fillo
- First test tube baby: Louis Brown

